service: lubycon-event-gateway

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2
  stage: ${opt:stage, "alpha"}
  profile: lubycon-mgmt
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: true
  customDomain:
    domainName: ${self:custom.${self:provider.stage}.subDomainName}.lubycon.io
    stage: ${self:provider.stage}
    certificateArn: arn:aws:acm:us-east-1:554707519121:certificate/652be07a-1826-43e6-a66e-1b6c36855be9 # includes *.lubycon, *.alpha.lubycon
    autoDomain: true
  alpha:
    subDomainName: event-gateway.alpha
  production:
    subDomainName: event-gateway

functions:
  api:
    package:
      patterns:
        - app/*
    handler: app.main.handler
    #architectures: arm64 서울리전 나와라아...
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: any
          path: /{proxy+}